CREATE TABLE users (
  id SERIAL PRIMARY KEY,
 firstname VARCHAR(255)  NOT NULL,
 Surname VARCHAR(255)  NOT NULL,
  phoneNumber VARCHAR(255)  NOT NULL,
  address VARCHAR(255)  NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL
);
